name: Deploy Preview

on:
  issue_comment:
    types: [created]

jobs:
  deploy:
    if: contains(github.event.comment.body, '/preview up')
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install cloudflared
        run: |
          wget https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
          sudo dpkg -i cloudflared-linux-amd64.deb

      - name: Start Cloudflare Tunnel
        id: tunnel
        run: |
          # Start cloudflared in background and write logs to a file
          cloudflared tunnel --url http://localhost:5000 --no-autoupdate > cloudflared.log 2>&1 &
          # Wait a few seconds for it to initialize
          sleep 5
          # Extract the tunnel URL from the logs
          url=$(grep -o "https://.*trycloudflare.com" cloudflared.log | head -n 1)
          echo "TUNNEL_URL=$url" >> $GITHUB_ENV

      - name: Post comment with URL
        run: |
          gh pr comment ${{ github.event.pull_request.number }} \
            --body "🚀 Preview available at: ${{ env.TUNNEL_URL }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run the app
        run: |
          pip install -r ./requirements.txt
          python3 ./app.py

      # - name: Build and Run Backend
      #   run: |
      #     docker build -t backend .
      #     docker run -d -p 8000:8000 backend

      # - name: Expose with Cloudflare Tunnel
      #   uses: cloudflare/cloudflare-tunnel-action@v2
      #   with:
      #     credentials: ${{ secrets.CLOUDFLARE_TUNNEL_CRED }}
      #     hostname: pr-${{ github.event.issue.number }}.myapp.dev
      #     service: http://localhost:8000

      # - name: Comment with Preview URL
      #   uses: marocchino/sticky-pull-request-comment@v2
      #   with:
      #     message: |
      #       🚀 Preview ready: https://pr-${{ github.event.issue.number }}.myapp.dev
